server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ascsoftdev/spring-cloud-config-store
          search-paths:
          - '*service'
        bootstrap: false
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'